<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{a5dab3a8-f5a9-4bfc-aa72-b7ae8c95de15}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    A : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[A := TRUE; //Comment]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>