name: FormatCode
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  format:
    runs-on: windows-latest
    env:
      InstallationFolder: "\\GeBa Engineering\\STweep CLI"
      SettingsFilePath: "\\GeBa Engineering\\STweep CLI\\Resources\\Default.STweep"
      
    steps:
      - uses: actions/checkout@v2

      - name: Install STweep CLI.    
        run: | 
          Invoke-WebRequest -Uri "https://www.stweep.com/wp-content/uploads/STweep.CLI/LatestRelease/STweep.CLI.Installer.msi" -Outfile "$HOME\Downloads\STweep.msi"                    
          $params = '/i',"$HOME\Downloads\STweep.msi",'/quiet'
          $p = Start-Process 'msiexec.exe' -ArgumentList $params -NoNewWindow -Wait -PassThru
          echo $p.ExitCode                    
          echo "${env:ProgramFiles(x86)}${env:InstallationFolder}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Activate STweep CLI.    
        run: |
          &STweep.CLI license-activate -k ${{secrets.STWEEPCLILICENSEKEY}} -a
        
      - name: Format code    
        run: |
          echo "${env:ProgramFiles(x86)}${env:SettingsFilePath}"
          &STweep.CLI format --path (Resolve-Path .\).Path --settingsFile "${env:ProgramFiles(x86)}${env:SettingsFilePath}"
        
      - name: Deactivate license
        if: always()
        run: |
          &STweep.CLI license-deactivate
        
        
