name: FormatCode
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and activate STweep CLI.    
        run: | 
          Invoke-WebRequest -Uri "https://www.stweep.com/wp-content/uploads/STweep.CLI/STweep.CLI%201.0.0-Beta/STweep.CLI.Installer.msi" -Outfile "$HOME\Downloads\STweep.msi"                    
          $params = '/i',"$HOME\Downloads\STweep.msi",'/quiet'
          $p = Start-Process 'msiexec.exe' -ArgumentList $params -NoNewWindow -Wait -PassThru
          echo $p.ExitCode                    
          echo "${env:ProgramFiles(x86)}\GeBa Engineering\STweep CLI" >> $GITHUB_PATH
          
      - name: Activate STweep CLI.    
        shell: powershell
        run: &STweep.CLI license-activate -k 123 -a


