name: FormatCode
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and activate STweep CLI.
        run: | 
          Invoke-WebRequest -Uri "https://www.stweep.com/wp-content/uploads/STweep.CLI/STweep.CLI%201.0.0-Beta/STweep.CLI.Installer.msi" -Outfile "$HOME\Downloads\STweep.msi"
          msiexec.exe /i "$HOME\Downloads\STweep.msi" /quiet
          STweep.CLI license-activate -k 123 -a


